### ISSUE TITLE
Setup a stale bot in this repository

### ISSUE THREAD

**Issue by luisan00** [btcven/locha-mesh-chat#25]
## Setup stale-bot
Old issues maybe difficult to handle,  for this, we can install a 'stale-bot' for to handle old issues

### How to install the bot
It must be inside the root folder in .github/stale.yml containing:
```yml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - important
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
  If you think this is an important issue, notify it directly by email to: contacto@bitcoinvenezuela.com 
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
```
