### ISSUE TITLE
Add travis-ci file

### ISSUE THREAD

**Issue by luisan00** [btcven/locha-mesh-chat#43]
**Travis-ci for continuous integration**
we need to automate some stages, so travis can cover this

**Describe the solution you'd like**
Using travis-ci for continuous integration  is an easy and fast option.
Add a file called `.travis.yml` to root folder containing:
```yaml
language: node_js
node_js:
- "10"
```
